services:
  postgres:
    image: 'postgres:18.1'
    environment:
      - 'POSTGRES_DB=entries'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASS}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '${POSTGRES_PORT}:5432'

  redis:
    image: 'redis/redis-stack:latest'
    labels:
      - "org.springframework.boot.service-connection=redis"
    ports:
      - '${REDIS_PORT}:6379'